### ISSUE TITLE
DB and Server Changes

### ISSUE THREAD

**Issue by raviteja-bhupatiraju** [NCBI-Hackathons/Visualizing_MeSH_Term_Interaction_Over_Time#3]
- removed year matching in chart search
- removed docs with 0 as year (about 10K)
- removed docs with empty mesh list (3M)

The later two should be excluded while loading the database, next time.
Removing year matching improves performance somewhat.

**Comment by SatyaSR** [comment]
We should record exact numbers for the publication.
